/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface": "#faf8ff",
        "on-background": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#6f3dd9",
        "on-secondary-fixed-variant": "#005236",
        "primary-fixed": "#e2dfff",
        "secondary": "#006c49",
        "on-tertiary-container": "#e3d5ff",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-variant": "#dae2fd",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        // Darkened from #777587: the original only reached 4.26:1 on the page
        // background and 3.86:1 on surface-container, failing AA for the small
        // uppercase labels this token carries.
        "outline": "#6b6980",
        "tertiary-fixed": "#e9ddff",
        "inverse-surface": "#283044",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#00714d",
        "background": "#faf8ff",
        "primary": "#3525cd",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed": "#23005c",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed-dim": "#d0bcff",
        "on-primary-container": "#dad7ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "inverse-on-surface": "#eef0ff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "surface-container-highest": "#dae2fd",
        "tertiary": "#571ac0",
        "outline-variant": "#c7c4d8",
        "primary-container": "#4f46e5",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary": "#ffffff",
        "surface-dim": "#d2d9f4",

        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "margin": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "mono-data": ["JetBrains Mono"],
        "title-sm": ["Inter"],
        "title-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
