export enum UserRole {
  PLATFORM_OWNER = 'PLATFORM_OWNER',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  DEPARTMENT_REVIEWER = 'DEPARTMENT_REVIEWER',
  FACULTY = 'FACULTY',
  STUDENT = 'STUDENT',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum IssueStatus {
  IDENTIFIED = 'IDENTIFIED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTION_PLANNED = 'ACTION_PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  ARCHIVED = 'ARCHIVED',
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  NEUTRAL = 'NEUTRAL',
  MIXED = 'MIXED',
}
